# Generated by Django 5.1 on 2024-08-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_otp_user_otp_created_at_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
