# Generated by Django 5.1 on 2024-08-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='metier',
            name='label_metier',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom du métier'),
        ),
        migrations.AlterField(
            model_name='metier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de Modification'),
        ),
    ]
