# Generated by Django 5.1 on 2024-08-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_metier_created_at_alter_metier_label_metier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Code OTP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Creation du code OTP'),
        ),
    ]
