# Generated by Django 5.1 on 2024-09-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_category_remove_artisan_quartier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='metier',
            options={'verbose_name': 'Métier', 'verbose_name_plural': 'Métiers'},
        ),
        migrations.AlterField(
            model_name='artisan',
            name='note',
            field=models.FloatField(blank=True, null=True, verbose_name="Note de l'artisan"),
        ),
    ]
